/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: true,

  async redirects() {
    return [
      // Old /town-state/ format → new /movers-town-state/
      { source: '/enfield-ct', destination: '/movers-enfield-ct', permanent: true },
      { source: '/enfield-ct/', destination: '/movers-enfield-ct', permanent: true },
      { source: '/somers-ct', destination: '/movers-somers-ct', permanent: true },
      { source: '/somers-ct/', destination: '/movers-somers-ct', permanent: true },
      { source: '/springfield-ma', destination: '/movers-springfield-ma', permanent: true },
      { source: '/springfield-ma/', destination: '/movers-springfield-ma', permanent: true },
      { source: '/suffield-ct', destination: '/movers-suffield-ct', permanent: true },
      { source: '/suffield-ct/', destination: '/movers-suffield-ct', permanent: true },
      { source: '/vernon-ct', destination: '/movers-vernon-ct', permanent: true },
      { source: '/vernon-ct/', destination: '/movers-vernon-ct', permanent: true },
      { source: '/bloomfield-ct', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/bloomfield-ct/', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/avon-ct', destination: '/movers-avon-ct', permanent: true },
      { source: '/avon-ct/', destination: '/movers-avon-ct', permanent: true },
      { source: '/east-windsor-ct', destination: '/movers-east-windsor-ct', permanent: true },
      { source: '/east-windsor-ct/', destination: '/movers-east-windsor-ct', permanent: true },
      { source: '/windsor-locks-ct', destination: '/movers-windsor-locks-ct', permanent: true },
      { source: '/windsor-locks-ct/', destination: '/movers-windsor-locks-ct', permanent: true },
      { source: '/farmington-ct', destination: '/movers-farmington-ct', permanent: true },
      { source: '/farmington-ct/', destination: '/movers-farmington-ct', permanent: true },
      { source: '/glastonbury-ct', destination: '/movers-glastonbury-ct', permanent: true },
      { source: '/glastonbury-ct/', destination: '/movers-glastonbury-ct', permanent: true },
      { source: '/hartford-ct', destination: '/movers-hartford-ct', permanent: true },
      { source: '/hartford-ct/', destination: '/movers-hartford-ct', permanent: true },
      { source: '/west-hartford-ct', destination: '/movers-west-hartford-ct', permanent: true },
      { source: '/west-hartford-ct/', destination: '/movers-west-hartford-ct', permanent: true },
      { source: '/simsbury-ct', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/simsbury-ct/', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/windsor-ct', destination: '/movers-windsor-ct', permanent: true },
      { source: '/windsor-ct/', destination: '/movers-windsor-ct', permanent: true },
      // Old /movers/town-state/ format → new /movers-town-state/
      { source: '/movers/enfield-ct', destination: '/movers-enfield-ct', permanent: true },
      { source: '/movers/enfield-ct/', destination: '/movers-enfield-ct', permanent: true },
      { source: '/movers/somers-ct', destination: '/movers-somers-ct', permanent: true },
      { source: '/movers/somers-ct/', destination: '/movers-somers-ct', permanent: true },
      { source: '/movers/windsor-ct', destination: '/movers-windsor-ct', permanent: true },
      { source: '/movers/windsor-ct/', destination: '/movers-windsor-ct', permanent: true },
      { source: '/movers/farmington-ct', destination: '/movers-farmington-ct', permanent: true },
      { source: '/movers/farmington-ct/', destination: '/movers-farmington-ct', permanent: true },
      { source: '/movers/bloomfield-ct', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/movers/bloomfield-ct/', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/movers/east-granby-ct', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/movers/east-granby-ct/', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/movers/ellington-ct', destination: '/movers-ellington-ct', permanent: true },
      { source: '/movers/ellington-ct/', destination: '/movers-ellington-ct', permanent: true },
      { source: '/movers/simsbury-ct', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/movers/simsbury-ct/', destination: '/movers-simsbury-ct', permanent: true },
      // Old blog/article style URLs
      { source: '/movers-in-hartford-ct-your-ticket-to-a-stress-free-move', destination: '/movers-hartford-ct', permanent: true },
      { source: '/movers-in-hartford-ct-your-ticket-to-a-stress-free-move/', destination: '/movers-hartford-ct', permanent: true },
      { source: '/movers-in-hartford-ct-your-ticket-to-a-stress-free-move-2', destination: '/movers-hartford-ct', permanent: true },
      { source: '/movers-in-hartford-ct-your-ticket-to-a-stress-free-move-2/', destination: '/movers-hartford-ct', permanent: true },
      // service-areas hub redirects (old slug format → new movers- format)
      { source: '/service-areas/enfield-ct', destination: '/movers-enfield-ct', permanent: true },
      { source: '/service-areas/enfield-ct/', destination: '/movers-enfield-ct', permanent: true },
      { source: '/service-areas/somers-ct', destination: '/movers-somers-ct', permanent: true },
      { source: '/service-areas/somers-ct/', destination: '/movers-somers-ct', permanent: true },
      { source: '/service-areas/suffield-ct', destination: '/movers-suffield-ct', permanent: true },
      { source: '/service-areas/suffield-ct/', destination: '/movers-suffield-ct', permanent: true },
      { source: '/service-areas/east-windsor-ct', destination: '/movers-east-windsor-ct', permanent: true },
      { source: '/service-areas/east-windsor-ct/', destination: '/movers-east-windsor-ct', permanent: true },
      { source: '/service-areas/ellington-ct', destination: '/movers-ellington-ct', permanent: true },
      { source: '/service-areas/ellington-ct/', destination: '/movers-ellington-ct', permanent: true },
      { source: '/service-areas/windsor-ct', destination: '/movers-windsor-ct', permanent: true },
      { source: '/service-areas/windsor-ct/', destination: '/movers-windsor-ct', permanent: true },
      { source: '/service-areas/windsor-locks-ct', destination: '/movers-windsor-locks-ct', permanent: true },
      { source: '/service-areas/windsor-locks-ct/', destination: '/movers-windsor-locks-ct', permanent: true },
      { source: '/service-areas/bloomfield-ct', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/service-areas/bloomfield-ct/', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/service-areas/east-granby-ct', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/service-areas/east-granby-ct/', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/service-areas/granby-ct', destination: '/movers-granby-ct', permanent: true },
      { source: '/service-areas/granby-ct/', destination: '/movers-granby-ct', permanent: true },
      { source: '/service-areas/simsbury-ct', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/service-areas/simsbury-ct/', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/service-areas/glastonbury-ct', destination: '/movers-glastonbury-ct', permanent: true },
      { source: '/service-areas/glastonbury-ct/', destination: '/movers-glastonbury-ct', permanent: true },
      { source: '/service-areas/avon-ct', destination: '/movers-avon-ct', permanent: true },
      { source: '/service-areas/avon-ct/', destination: '/movers-avon-ct', permanent: true },
      { source: '/service-areas/farmington-ct', destination: '/movers-farmington-ct', permanent: true },
      { source: '/service-areas/farmington-ct/', destination: '/movers-farmington-ct', permanent: true },
      { source: '/service-areas/newington-ct', destination: '/movers-newington-ct', permanent: true },
      { source: '/service-areas/newington-ct/', destination: '/movers-newington-ct', permanent: true },
      { source: '/service-areas/tolland-ct', destination: '/movers-tolland-ct', permanent: true },
      { source: '/service-areas/tolland-ct/', destination: '/movers-tolland-ct', permanent: true },
      { source: '/service-areas/vernon-ct', destination: '/movers-vernon-ct', permanent: true },
      { source: '/service-areas/vernon-ct/', destination: '/movers-vernon-ct', permanent: true },
      { source: '/service-areas/west-hartford-ct', destination: '/movers-west-hartford-ct', permanent: true },
      { source: '/service-areas/west-hartford-ct/', destination: '/movers-west-hartford-ct', permanent: true },
      { source: '/service-areas/wethersfield-ct', destination: '/movers-wethersfield-ct', permanent: true },
      { source: '/service-areas/wethersfield-ct/', destination: '/movers-wethersfield-ct', permanent: true },
      { source: '/service-areas/springfield-ma', destination: '/movers-springfield-ma', permanent: true },
      { source: '/service-areas/springfield-ma/', destination: '/movers-springfield-ma', permanent: true },
      { source: '/service-areas/agawam-ma', destination: '/movers-agawam-ma', permanent: true },
      { source: '/service-areas/agawam-ma/', destination: '/movers-agawam-ma', permanent: true },
    ];
  },
};

module.exports = nextConfig;
