/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: true,

  async redirects() {
    return [
      // Old /town-state/ format → new /movers-town-state/
      { source: '/enfield-ct', destination: '/movers-enfield-ct', permanent: true },
      { source: '/enfield-ct/', destination: '/movers-enfield-ct', permanent: true },
      { source: '/somers-ct', destination: '/movers-somers-ct', permanent: true },
      { source: '/somers-ct/', destination: '/movers-somers-ct', permanent: true },
      { source: '/springfield-ma', destination: '/movers-springfield-ma', permanent: true },
      { source: '/springfield-ma/', destination: '/movers-springfield-ma', permanent: true },
      { source: '/suffield-ct', destination: '/movers-suffield-ct', permanent: true },
      { source: '/suffield-ct/', destination: '/movers-suffield-ct', permanent: true },
      { source: '/vernon-ct', destination: '/movers-vernon-ct', permanent: true },
      { source: '/vernon-ct/', destination: '/movers-vernon-ct', permanent: true },
      { source: '/bloomfield-ct', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/bloomfield-ct/', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/avon-ct', destination: '/movers-avon-ct', permanent: true },
      { source: '/avon-ct/', destination: '/movers-avon-ct', permanent: true },
      { source: '/east-windsor-ct', destination: '/movers-east-windsor-ct', permanent: true },
      { source: '/east-windsor-ct/', destination: '/movers-east-windsor-ct', permanent: true },
      { source: '/windsor-locks-ct', destination: '/movers-windsor-locks-ct', permanent: true },
      { source: '/windsor-locks-ct/', destination: '/movers-windsor-locks-ct', permanent: true },
      { source: '/farmington-ct', destination: '/movers-farmington-ct', permanent: true },
      { source: '/farmington-ct/', destination: '/movers-farmington-ct', permanent: true },
      { source: '/glastonbury-ct', destination: '/movers-glastonbury-ct', permanent: true },
      { source: '/glastonbury-ct/', destination: '/movers-glastonbury-ct', permanent: true },
      { source: '/hartford-ct', destination: '/movers-hartford-ct', permanent: true },
      { source: '/hartford-ct/', destination: '/movers-hartford-ct', permanent: true },
      { source: '/west-hartford-ct', destination: '/movers-west-hartford-ct', permanent: true },
      { source: '/west-hartford-ct/', destination: '/movers-west-hartford-ct', permanent: true },
      { source: '/simsbury-ct', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/simsbury-ct/', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/windsor-ct', destination: '/movers-windsor-ct', permanent: true },
      { source: '/windsor-ct/', destination: '/movers-windsor-ct', permanent: true },
      // Old /movers/town-state/ format → new /movers-town-state/
      { source: '/movers/enfield-ct', destination: '/movers-enfield-ct', permanent: true },
      { source: '/movers/enfield-ct/', destination: '/movers-enfield-ct', permanent: true },
      { source: '/movers/somers-ct', destination: '/movers-somers-ct', permanent: true },
      { source: '/movers/somers-ct/', destination: '/movers-somers-ct', permanent: true },
      { source: '/movers/windsor-ct', destination: '/movers-windsor-ct', permanent: true },
      { source: '/movers/windsor-ct/', destination: '/movers-windsor-ct', permanent: true },
      { source: '/movers/farmington-ct', destination: '/movers-farmington-ct', permanent: true },
      { source: '/movers/farmington-ct/', destination: '/movers-farmington-ct', permanent: true },
      { source: '/movers/bloomfield-ct', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/movers/bloomfield-ct/', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/movers/east-granby-ct', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/movers/east-granby-ct/', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/movers/ellington-ct', destination: '/movers-ellington-ct', permanent: true },
      { source: '/movers/ellington-ct/', destination: '/movers-ellington-ct', permanent: true },
      { source: '/movers/simsbury-ct', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/movers/simsbury-ct/', destination: '/movers-simsbury-ct', permanent: true },
      // Old blog/article style URLs
      { source: '/movers-in-hartford-ct-your-ticket-to-a-stress-free-move', destination: '/movers-hartford-ct', permanent: true },
      { source: '/movers-in-hartford-ct-your-ticket-to-a-stress-free-move/', destination: '/movers-hartford-ct', permanent: true },
      { source: '/movers-in-hartford-ct-your-ticket-to-a-stress-free-move-2', destination: '/movers-hartford-ct', permanent: true },
      { source: '/movers-in-hartford-ct-your-ticket-to-a-stress-free-move-2/', destination: '/movers-hartford-ct', permanent: true },
      // service-areas hub redirects (old slug format → new movers- format)
      { source: '/service-areas/enfield-ct', destination: '/movers-enfield-ct', permanent: true },
      { source: '/service-areas/enfield-ct/', destination: '/movers-enfield-ct', permanent: true },
      { source: '/service-areas/somers-ct', destination: '/movers-somers-ct', permanent: true },
      { source: '/service-areas/somers-ct/', destination: '/movers-somers-ct', permanent: true },
      { source: '/service-areas/suffield-ct', destination: '/movers-suffield-ct', permanent: true },
      { source: '/service-areas/suffield-ct/', destination: '/movers-suffield-ct', permanent: true },
      { source: '/service-areas/east-windsor-ct', destination: '/movers-east-windsor-ct', permanent: true },
      { source: '/service-areas/east-windsor-ct/', destination: '/movers-east-windsor-ct', permanent: true },
      { source: '/service-areas/ellington-ct', destination: '/movers-ellington-ct', permanent: true },
      { source: '/service-areas/ellington-ct/', destination: '/movers-ellington-ct', permanent: true },
      { source: '/service-areas/windsor-ct', destination: '/movers-windsor-ct', permanent: true },
      { source: '/service-areas/windsor-ct/', destination: '/movers-windsor-ct', permanent: true },
      { source: '/service-areas/windsor-locks-ct', destination: '/movers-windsor-locks-ct', permanent: true },
      { source: '/service-areas/windsor-locks-ct/', destination: '/movers-windsor-locks-ct', permanent: true },
      { source: '/service-areas/bloomfield-ct', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/service-areas/bloomfield-ct/', destination: '/movers-bloomfield-ct', permanent: true },
      { source: '/service-areas/east-granby-ct', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/service-areas/east-granby-ct/', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/service-areas/granby-ct', destination: '/movers-granby-ct', permanent: true },
      { source: '/service-areas/granby-ct/', destination: '/movers-granby-ct', permanent: true },
      { source: '/service-areas/simsbury-ct', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/service-areas/simsbury-ct/', destination: '/movers-simsbury-ct', permanent: true },
      { source: '/service-areas/glastonbury-ct', destination: '/movers-glastonbury-ct', permanent: true },
      { source: '/service-areas/glastonbury-ct/', destination: '/movers-glastonbury-ct', permanent: true },
      { source: '/service-areas/avon-ct', destination: '/movers-avon-ct', permanent: true },
      { source: '/service-areas/avon-ct/', destination: '/movers-avon-ct', permanent: true },
      { source: '/service-areas/farmington-ct', destination: '/movers-farmington-ct', permanent: true },
      { source: '/service-areas/farmington-ct/', destination: '/movers-farmington-ct', permanent: true },
      { source: '/service-areas/newington-ct', destination: '/movers-newington-ct', permanent: true },
      { source: '/service-areas/newington-ct/', destination: '/movers-newington-ct', permanent: true },
      { source: '/service-areas/tolland-ct', destination: '/movers-tolland-ct', permanent: true },
      { source: '/service-areas/tolland-ct/', destination: '/movers-tolland-ct', permanent: true },
      { source: '/service-areas/vernon-ct', destination: '/movers-vernon-ct', permanent: true },
      { source: '/service-areas/vernon-ct/', destination: '/movers-vernon-ct', permanent: true },
      { source: '/service-areas/west-hartford-ct', destination: '/movers-west-hartford-ct', permanent: true },
      { source: '/service-areas/west-hartford-ct/', destination: '/movers-west-hartford-ct', permanent: true },
      { source: '/service-areas/wethersfield-ct', destination: '/movers-wethersfield-ct', permanent: true },
      { source: '/service-areas/wethersfield-ct/', destination: '/movers-wethersfield-ct', permanent: true },
      { source: '/service-areas/springfield-ma', destination: '/movers-springfield-ma', permanent: true },
      { source: '/service-areas/springfield-ma/', destination: '/movers-springfield-ma', permanent: true },
      { source: '/service-areas/agawam-ma', destination: '/movers-agawam-ma', permanent: true },
      { source: '/service-areas/agawam-ma/', destination: '/movers-agawam-ma', permanent: true },
      // Blog post redirects from old WordPress URLs
      { source: '/moving-companies-in-connecticut-how-to-choose-the-best-one-in-2024/', destination: '/blog/how-to-choose-a-moving-company-in-connecticut/', permanent: true },
      { source: '/moving-companies-in-connecticut-how-to-choose-the-best-one-in-2024', destination: '/blog/how-to-choose-a-moving-company-in-connecticut/', permanent: true },
      { source: '/moving-with-castle-express/', destination: '/blog/why-castle-express/', permanent: true },
      { source: '/moving-with-castle-express', destination: '/blog/why-castle-express/', permanent: true },
      { source: '/moving-in-and-living-to-ellington-a-practical-guide-in-2024/', destination: '/blog/moving-to-ellington-ct/', permanent: true },
      { source: '/moving-in-and-living-to-ellington-a-practical-guide-in-2024', destination: '/blog/moving-to-ellington-ct/', permanent: true },
      { source: '/moving-and-packing-fragile-items-heres-what-you-should-do-and-not-do/', destination: '/blog/how-to-pack-fragile-items-for-a-move/', permanent: true },
      { source: '/moving-and-packing-fragile-items-heres-what-you-should-do-and-not-do', destination: '/blog/how-to-pack-fragile-items-for-a-move/', permanent: true },
      { source: '/moving-company-ct-how-to-avoid-common-hiring-mistakes/', destination: '/blog/how-to-avoid-getting-burned-by-a-moving-company/', permanent: true },
      { source: '/moving-company-ct-how-to-avoid-common-hiring-mistakes', destination: '/blog/how-to-avoid-getting-burned-by-a-moving-company/', permanent: true },
      // Old blog index redirects
      { source: '/blogs/', destination: '/blog/', permanent: true },
      { source: '/blogs', destination: '/blog/', permanent: true },
      { source: '/moving-tips/', destination: '/blog/', permanent: true },
      { source: '/moving-tips', destination: '/blog/', permanent: true },
      // Old WordPress URLs with backlinks
      { source: '/about-us', destination: '/about', permanent: true },
      { source: '/about-us/', destination: '/about', permanent: true },
      { source: '/wp-content/:path*', destination: '/', permanent: true },
      // Missing root-level town redirects
      { source: '/newington-ct', destination: '/movers-newington-ct', permanent: true },
      { source: '/newington-ct/', destination: '/movers-newington-ct', permanent: true },
      { source: '/granby-ct', destination: '/movers-granby-ct', permanent: true },
      { source: '/granby-ct/', destination: '/movers-granby-ct', permanent: true },
      { source: '/tolland-ct', destination: '/movers-tolland-ct', permanent: true },
      { source: '/tolland-ct/', destination: '/movers-tolland-ct', permanent: true },
      { source: '/ellington-ct', destination: '/movers-ellington-ct', permanent: true },
      { source: '/ellington-ct/', destination: '/movers-ellington-ct', permanent: true },
      { source: '/east-granby-ct', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/east-granby-ct/', destination: '/movers-east-granby-ct', permanent: true },
      { source: '/suffield-ct', destination: '/movers-suffield-ct', permanent: true },
      { source: '/suffield-ct/', destination: '/movers-suffield-ct', permanent: true },
      // Old WordPress site pages
      { source: '/contact-us', destination: '/contact', permanent: true },
      { source: '/contact-us/', destination: '/contact', permanent: true },
      { source: '/offer', destination: '/contact', permanent: true },
      { source: '/offer/', destination: '/contact', permanent: true },
      { source: '/reviews-accreditation', destination: '/about', permanent: true },
      { source: '/reviews-accreditation/', destination: '/about', permanent: true },
      { source: '/commercial-mover', destination: '/services', permanent: true },
      { source: '/commercial-mover/', destination: '/services', permanent: true },
      { source: '/residential-mover', destination: '/services', permanent: true },
      { source: '/residential-mover/', destination: '/services', permanent: true },
      { source: '/storage-with-climate-control', destination: '/services', permanent: true },
      { source: '/storage-with-climate-control/', destination: '/services', permanent: true },
      { source: '/specialty-moving-service', destination: '/services', permanent: true },
      { source: '/specialty-moving-service/', destination: '/services', permanent: true },
      // Old sitemap URLs
      { source: '/post-sitemap.xml', destination: '/sitemap.xml', permanent: true },
      { source: '/sitemaps.xml', destination: '/sitemap.xml', permanent: true },
      // Old WordPress blog/service URLs from GA4
      { source: '/mastering-piano-moving-in-ct-expert-tips-for-safe-relocation', destination: '/services/specialty-moving', permanent: true },
      { source: '/mastering-piano-moving-in-ct-expert-tips-for-safe-relocation/', destination: '/services/specialty-moving', permanent: true },
      { source: '/labor-only-moving-for-small-businesses', destination: '/services', permanent: true },
      { source: '/labor-only-moving-for-small-businesses/', destination: '/services', permanent: true },
      { source: '/mastering-piano', destination: '/services/specialty-moving', permanent: true },
      { source: '/mastering-piano/', destination: '/services/specialty-moving', permanent: true },
      // Old WordPress blog posts from GA4
      { source: '/top-10-tips-for-choosing-the-right-moving-company-in-enfield-ct', destination: '/blog', permanent: true },
      { source: '/top-10-tips-for-choosing-the-right-moving-company-in-enfield-ct/', destination: '/blog', permanent: true },
      { source: '/affordable-towns-in-ct-guide-by-a-moving-company-in-ct', destination: '/blog', permanent: true },
      { source: '/affordable-towns-in-ct-guide-by-a-moving-company-in-ct/', destination: '/blog', permanent: true },
      { source: '/packing-services-do-they-really-save-you-time-and-effort-during-a-move', destination: '/blog', permanent: true },
      { source: '/packing-services-do-they-really-save-you-time-and-effort-during-a-move/', destination: '/blog', permanent: true },
      // Old /movers/[town]/ wildcard redirects (catch subpaths)
      { source: '/movers/windsor-ct/:path*', destination: '/movers-windsor-ct/', permanent: true },
      { source: '/movers/simsbury-ct/:path*', destination: '/movers-simsbury-ct/', permanent: true },
      { source: '/movers/farmington-ct/:path*', destination: '/movers-farmington-ct/', permanent: true },
      { source: '/movers/newington-ct/:path*', destination: '/movers-newington-ct/', permanent: true },
      { source: '/movers/avon-ct/:path*', destination: '/movers-avon-ct/', permanent: true },
      { source: '/movers/east-windsor-ct/:path*', destination: '/movers-east-windsor-ct/', permanent: true },
      { source: '/movers/springfield-ma/:path*', destination: '/movers-springfield-ma/', permanent: true },
      { source: '/movers/suffield-ct/:path*', destination: '/movers-suffield-ct/', permanent: true },
      { source: '/movers/granby-ct/:path*', destination: '/movers-granby-ct/', permanent: true },
      { source: '/movers/east-granby-ct/:path*', destination: '/movers-east-granby-ct/', permanent: true },
      { source: '/movers/ellington-ct/:path*', destination: '/movers-ellington-ct/', permanent: true },
      { source: '/movers/enfield-ct/:path*', destination: '/movers-enfield-ct/', permanent: true },
      { source: '/movers/tolland-ct/:path*', destination: '/movers-tolland-ct/', permanent: true },
      { source: '/movers/somers-ct/:path*', destination: '/movers-somers-ct/', permanent: true },
      { source: '/movers/windsor-locks-ct/:path*', destination: '/movers-windsor-locks-ct/', permanent: true },
      { source: '/movers/', destination: '/service-areas/', permanent: true },
      { source: '/movers', destination: '/service-areas/', permanent: true },
      // Old service page URLs
      { source: '/services/piano-moving', destination: '/services', permanent: true },
      { source: '/services/piano-moving/', destination: '/services', permanent: true },
      { source: '/services/construction', destination: '/services', permanent: true },
      { source: '/services/construction/', destination: '/services', permanent: true },
      { source: '/services/you-pack-we-move', destination: '/services', permanent: true },
      { source: '/services/you-pack-we-move/', destination: '/services', permanent: true },
      { source: '/services/packing', destination: '/services/packing-services', permanent: true },
      { source: '/services/packing/', destination: '/services/packing-services', permanent: true },
      { source: '/services/commercial-moving', destination: '/services', permanent: true },
      { source: '/services/commercial-moving/', destination: '/services', permanent: true },
      // Old blog numeric URLs
      { source: '/blogs/:id/', destination: '/blog/', permanent: true },
      { source: '/blogs/:id', destination: '/blog/', permanent: true },
      // Old misc URLs
      { source: '/castleexpressmoving/about-us', destination: '/', permanent: true },
      { source: '/castleexpressmoving/about-us/', destination: '/', permanent: true },
      { source: '/embed', destination: '/', permanent: true },
      { source: '/embed/', destination: '/', permanent: true },
      { source: '/packing-tips-for-fragile-and-specialty-items-pianos-antiques-safes-more', destination: '/blog', permanent: true },
      { source: '/packing-tips-for-fragile-and-specialty-items-pianos-antiques-safes-more/', destination: '/blog', permanent: true },
    ];
  },
};

module.exports = nextConfig;
