// lib/cityData.js
// Castle Express Moving — Complete 82-town SEO data
// Generated from Master Keyword Plan
// URL format: castleexpressmoving.com/movers-[town]-[state]/

export const CITY_DATA = [
  {
    "town": "East Windsor",
    "state": "CT",
    "stateFull": "Connecticut",
    "tier": "Tier 1 - Priority",
    "drive": "15 min",
    "slug": "movers-east-windsor-ct",
    "title": "Best Movers in East Windsor, CT | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in East Windsor, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in East Windsor, Connecticut",
    "h2_local": "Local Moving Services in East Windsor",
    "h2_ld": "Long Distance Moving from East Windsor, CT",
    "h2_specialty": "Piano & Specialty Movers in East Windsor",
    "h2_packing": "Packing Services in East Windsor, CT",
    "h2_commercial": "Commercial Moving in East Windsor",
    "h2_why": "Why East Windsor Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in East Windsor Today!"
  },
  {
    "town": "Ellington",
    "state": "CT",
    "stateFull": "Connecticut",
    "tier": "Tier 1 - Priority",
    "drive": "18-20 min",
    "slug": "movers-ellington-ct",
    "title": "Best Movers in Ellington, CT | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Ellington, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Ellington, Connecticut",
    "h2_local": "Local Moving Services in Ellington",
    "h2_ld": "Long Distance Moving from Ellington, CT",
    "h2_specialty": "Piano & Specialty Movers in Ellington",
    "h2_packing": "Packing Services in Ellington, CT",
    "h2_commercial": "Commercial Moving in Ellington",
    "h2_why": "Why Ellington Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Ellington Today!"
  },
  {
    "town": "Enfield",
    "state": "CT",
    "stateFull": "Connecticut",
    "tier": "Tier 1 - Priority",
    "drive": "0 min (home base)",
    "slug": "movers-enfield-ct",
    "title": "Best Movers in Enfield, CT | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Enfield, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Enfield, Connecticut",
    "h2_local": "Local Moving Services in Enfield",
    "h2_ld": "Long Distance Moving from Enfield, CT",
    "h2_specialty": "Piano & Specialty Movers in Enfield",
    "h2_packing": "Packing Services in Enfield, CT",
    "h2_commercial": "Commercial Moving in Enfield",
    "h2_why": "Why Enfield Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Enfield Today!"
  },
  {
    "town": "Somers",
    "state": "CT",
    "stateFull": "Connecticut",
    "tier": "Tier 1 - Priority",
    "drive": "12 min",
    "slug": "movers-somers-ct",
    "title": "Best Movers in Somers, CT | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Somers, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Somers, Connecticut",
    "h2_local": "Local Moving Services in Somers",
    "h2_ld": "Long Distance Moving from Somers, CT",
    "h2_specialty": "Piano & Specialty Movers in Somers",
    "h2_packing": "Packing Services in Somers, CT",
    "h2_commercial": "Commercial Moving in Somers",
    "h2_why": "Why Somers Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Somers Today!"
  },
  {
    "town": "South Windsor",
    "state": "CT",
    "stateFull": "Connecticut",
    "tier": "Tier 1 - Priority",
    "drive": "18-20 min",
    "slug": "movers-south-windsor-ct",
    "title": "Best Movers in South Windsor, CT | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in South Windsor, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in South Windsor, Connecticut",
    "h2_local": "Local Moving Services in South Windsor",
    "h2_ld": "Long Distance Moving from South Windsor, CT",
    "h2_specialty": "Piano & Specialty Movers in South Windsor",
    "h2_packing": "Packing Services in South Windsor, CT",
    "h2_commercial": "Commercial Moving in South Windsor",
    "h2_why": "Why South Windsor Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in South Windsor Today!"
  },
  {
    "town": "Suffield",
    "state": "CT",
    "stateFull": "Connecticut",
    "tier": "Tier 1 - Priority",
    "drive": "12-15 min",
    "slug": "movers-suffield-ct",
    "title": "Best Movers in Suffield, CT | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Suffield, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Suffield, Connecticut",
    "h2_local": "Local Moving Services in Suffield",
    "h2_ld": "Long Distance Moving from Suffield, CT",
    "h2_specialty": "Piano & Specialty Movers in Suffield",
    "h2_packing": "Packing Services in Suffield, CT",
    "h2_commercial": "Commercial Moving in Suffield",
    "h2_why": "Why Suffield Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Suffield Today!"
  },
  {
    "town": "Windsor",
    "state": "CT",
    "stateFull": "Connecticut",
    "tier": "Tier 1 - Priority",
    "drive": "12-15 min",
    "slug": "movers-windsor-ct",
    "title": "Best Movers in Windsor, CT | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Windsor, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Windsor, Connecticut",
    "h2_local": "Local Moving Services in Windsor",
    "h2_ld": "Long Distance Moving from Windsor, CT",
    "h2_specialty": "Piano & Specialty Movers in Windsor",
    "h2_packing": "Packing Services in Windsor, CT",
    "h2_commercial": "Commercial Moving in Windsor",
    "h2_why": "Why Windsor Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Windsor Today!"
  },
  {
    "town": "Windsor Locks",
    "state": "CT",
    "stateFull": "Connecticut",
    "tier": "Tier 1 - Priority",
    "drive": "7 min",
    "slug": "movers-windsor-locks-ct",
    "title": "Best Movers in Windsor Locks, CT | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Windsor Locks, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Windsor Locks, Connecticut",
    "h2_local": "Local Moving Services in Windsor Locks",
    "h2_ld": "Long Distance Moving from Windsor Locks, CT",
    "h2_specialty": "Piano & Specialty Movers in Windsor Locks",
    "h2_packing": "Packing Services in Windsor Locks, CT",
    "h2_commercial": "Commercial Moving in Windsor Locks",
    "h2_why": "Why Windsor Locks Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Windsor Locks Today!"
  },
  {
    "town": "Agawam",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "12-15 min",
    "slug": "movers-agawam-ma",
    "title": "Best Movers in Agawam, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Agawam, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Agawam, Massachusetts",
    "h2_local": "Local Moving Services in Agawam",
    "h2_ld": "Long Distance Moving from Agawam, MA",
    "h2_specialty": "Piano & Specialty Movers in Agawam",
    "h2_packing": "Packing Services in Agawam, MA",
    "h2_commercial": "Commercial Moving in Agawam",
    "h2_why": "Why Agawam Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Agawam Today!"
  },
  {
    "town": "Chicopee",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "18-20 min",
    "slug": "movers-chicopee-ma",
    "title": "Best Movers in Chicopee, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Chicopee, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Chicopee, Massachusetts",
    "h2_local": "Local Moving Services in Chicopee",
    "h2_ld": "Long Distance Moving from Chicopee, MA",
    "h2_specialty": "Piano & Specialty Movers in Chicopee",
    "h2_packing": "Packing Services in Chicopee, MA",
    "h2_commercial": "Commercial Moving in Chicopee",
    "h2_why": "Why Chicopee Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Chicopee Today!"
  },
  {
    "town": "East Longmeadow",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "10-12 min",
    "slug": "movers-east-longmeadow-ma",
    "title": "Best Movers in East Longmeadow, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in East Longmeadow, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in East Longmeadow, Massachusetts",
    "h2_local": "Local Moving Services in East Longmeadow",
    "h2_ld": "Long Distance Moving from East Longmeadow, MA",
    "h2_specialty": "Piano & Specialty Movers in East Longmeadow",
    "h2_packing": "Packing Services in East Longmeadow, MA",
    "h2_commercial": "Commercial Moving in East Longmeadow",
    "h2_why": "Why East Longmeadow Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in East Longmeadow Today!"
  },
  {
    "town": "Hampden",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "25-30 min",
    "slug": "movers-hampden-ma",
    "title": "Best Movers in Hampden, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Hampden, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Hampden, Massachusetts",
    "h2_local": "Local Moving Services in Hampden",
    "h2_ld": "Long Distance Moving from Hampden, MA",
    "h2_specialty": "Piano & Specialty Movers in Hampden",
    "h2_packing": "Packing Services in Hampden, MA",
    "h2_commercial": "Commercial Moving in Hampden",
    "h2_why": "Why Hampden Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Hampden Today!"
  },
  {
    "town": "Holyoke",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "23-25 min",
    "slug": "movers-holyoke-ma",
    "title": "Best Movers in Holyoke, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Holyoke, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Holyoke, Massachusetts",
    "h2_local": "Local Moving Services in Holyoke",
    "h2_ld": "Long Distance Moving from Holyoke, MA",
    "h2_specialty": "Piano & Specialty Movers in Holyoke",
    "h2_packing": "Packing Services in Holyoke, MA",
    "h2_commercial": "Commercial Moving in Holyoke",
    "h2_why": "Why Holyoke Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Holyoke Today!"
  },
  {
    "town": "Longmeadow",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "10-12 min",
    "slug": "movers-longmeadow-ma",
    "title": "Best Movers in Longmeadow, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Longmeadow, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Longmeadow, Massachusetts",
    "h2_local": "Local Moving Services in Longmeadow",
    "h2_ld": "Long Distance Moving from Longmeadow, MA",
    "h2_specialty": "Piano & Specialty Movers in Longmeadow",
    "h2_packing": "Packing Services in Longmeadow, MA",
    "h2_commercial": "Commercial Moving in Longmeadow",
    "h2_why": "Why Longmeadow Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Longmeadow Today!"
  },
  {
    "town": "Ludlow",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "25-30 min",
    "slug": "movers-ludlow-ma",
    "title": "Best Movers in Ludlow, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Ludlow, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Ludlow, Massachusetts",
    "h2_local": "Local Moving Services in Ludlow",
    "h2_ld": "Long Distance Moving from Ludlow, MA",
    "h2_specialty": "Piano & Specialty Movers in Ludlow",
    "h2_packing": "Packing Services in Ludlow, MA",
    "h2_commercial": "Commercial Moving in Ludlow",
    "h2_why": "Why Ludlow Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Ludlow Today!"
  },
  {
    "town": "Southwick",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "30-35 min",
    "slug": "movers-southwick-ma",
    "title": "Best Movers in Southwick, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Southwick, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Southwick, Massachusetts",
    "h2_local": "Local Moving Services in Southwick",
    "h2_ld": "Long Distance Moving from Southwick, MA",
    "h2_specialty": "Piano & Specialty Movers in Southwick",
    "h2_packing": "Packing Services in Southwick, MA",
    "h2_commercial": "Commercial Moving in Southwick",
    "h2_why": "Why Southwick Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Southwick Today!"
  },
  {
    "town": "Springfield",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "18-20 min",
    "slug": "movers-springfield-ma",
    "title": "Best Movers in Springfield, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Springfield, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Springfield, Massachusetts",
    "h2_local": "Local Moving Services in Springfield",
    "h2_ld": "Long Distance Moving from Springfield, MA",
    "h2_specialty": "Piano & Specialty Movers in Springfield",
    "h2_packing": "Packing Services in Springfield, MA",
    "h2_commercial": "Commercial Moving in Springfield",
    "h2_why": "Why Springfield Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Springfield Today!"
  },
  {
    "town": "West Springfield",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "15-20 min",
    "slug": "movers-west-springfield-ma",
    "title": "Best Movers in West Springfield, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in West Springfield, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in West Springfield, Massachusetts",
    "h2_local": "Local Moving Services in West Springfield",
    "h2_ld": "Long Distance Moving from West Springfield, MA",
    "h2_specialty": "Piano & Specialty Movers in West Springfield",
    "h2_packing": "Packing Services in West Springfield, MA",
    "h2_commercial": "Commercial Moving in West Springfield",
    "h2_why": "Why West Springfield Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in West Springfield Today!"
  },
  {
    "town": "Westfield",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "30-35 min",
    "slug": "movers-westfield-ma",
    "title": "Best Movers in Westfield, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Westfield, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Westfield, Massachusetts",
    "h2_local": "Local Moving Services in Westfield",
    "h2_ld": "Long Distance Moving from Westfield, MA",
    "h2_specialty": "Piano & Specialty Movers in Westfield",
    "h2_packing": "Packing Services in Westfield, MA",
    "h2_commercial": "Commercial Moving in Westfield",
    "h2_why": "Why Westfield Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Westfield Today!"
  },
  {
    "town": "Wilbraham",
    "state": "MA",
    "stateFull": "Massachusetts",
    "tier": "Tier 1 - Priority",
    "drive": "20-25 min",
    "slug": "movers-wilbraham-ma",
    "title": "Best Movers in Wilbraham, MA | Castle Express Moving & Storage",
    "meta": "Looking for reliable movers in Wilbraham, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!",
    "h1": "Professional Movers in Wilbraham, Massachusetts",
    "h2_local": "Local Moving Services in Wilbraham",
    "h2_ld": "Long Distance Moving from Wilbraham, MA",
    "h2_specialty": "Piano & Specialty Movers in Wilbraham",
    "h2_packing": "Packing Services in Wilbraham, MA",
    "h2_commercial": "Commercial Moving in Wilbraham",
    "h2_why": "Why Wilbraham Residents Choose Castle Express",
    "cta": "Get a Free Moving Quote in Wilbraham Today!"
  },
  { "town": "Bloomfield", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "22-25 min", "slug": "movers-bloomfield-ct", "title": "Best Movers in Bloomfield, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Bloomfield, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Bloomfield, Connecticut", "h2_local": "Local Moving Services in Bloomfield", "h2_ld": "Long Distance Moving from Bloomfield, CT", "h2_specialty": "Piano & Specialty Movers in Bloomfield", "h2_packing": "Packing Services in Bloomfield, CT", "h2_commercial": "Commercial Moving in Bloomfield", "h2_why": "Why Bloomfield Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Bloomfield Today!" },
  { "town": "East Granby", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "20-25 min", "slug": "movers-east-granby-ct", "title": "Best Movers in East Granby, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in East Granby, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in East Granby, Connecticut", "h2_local": "Local Moving Services in East Granby", "h2_ld": "Long Distance Moving from East Granby, CT", "h2_specialty": "Piano & Specialty Movers in East Granby", "h2_packing": "Packing Services in East Granby, CT", "h2_commercial": "Commercial Moving in East Granby", "h2_why": "Why East Granby Residents Choose Castle Express", "cta": "Get a Free Moving Quote in East Granby Today!" },
  { "town": "East Hartford", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "20-22 min", "slug": "movers-east-hartford-ct", "title": "Best Movers in East Hartford, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in East Hartford, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in East Hartford, Connecticut", "h2_local": "Local Moving Services in East Hartford", "h2_ld": "Long Distance Moving from East Hartford, CT", "h2_specialty": "Piano & Specialty Movers in East Hartford", "h2_packing": "Packing Services in East Hartford, CT", "h2_commercial": "Commercial Moving in East Hartford", "h2_why": "Why East Hartford Residents Choose Castle Express", "cta": "Get a Free Moving Quote in East Hartford Today!" },
  { "town": "Glastonbury", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "25-28 min", "slug": "movers-glastonbury-ct", "title": "Best Movers in Glastonbury, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Glastonbury, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Glastonbury, Connecticut", "h2_local": "Local Moving Services in Glastonbury", "h2_ld": "Long Distance Moving from Glastonbury, CT", "h2_specialty": "Piano & Specialty Movers in Glastonbury", "h2_packing": "Packing Services in Glastonbury, CT", "h2_commercial": "Commercial Moving in Glastonbury", "h2_why": "Why Glastonbury Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Glastonbury Today!" },
  { "town": "Granby", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "25-28 min", "slug": "movers-granby-ct", "title": "Best Movers in Granby, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Granby, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Granby, Connecticut", "h2_local": "Local Moving Services in Granby", "h2_ld": "Long Distance Moving from Granby, CT", "h2_specialty": "Piano & Specialty Movers in Granby", "h2_packing": "Packing Services in Granby, CT", "h2_commercial": "Commercial Moving in Granby", "h2_why": "Why Granby Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Granby Today!" },
  { "town": "Hartford", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "19 min", "slug": "movers-hartford-ct", "title": "Best Movers in Hartford, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Hartford, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Hartford, Connecticut", "h2_local": "Local Moving Services in Hartford", "h2_ld": "Long Distance Moving from Hartford, CT", "h2_specialty": "Piano & Specialty Movers in Hartford", "h2_packing": "Packing Services in Hartford, CT", "h2_commercial": "Commercial Moving in Hartford", "h2_why": "Why Hartford Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Hartford Today!" },
  { "town": "Manchester", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "29-33 min", "slug": "movers-manchester-ct", "title": "Best Movers in Manchester, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Manchester, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Manchester, Connecticut", "h2_local": "Local Moving Services in Manchester", "h2_ld": "Long Distance Moving from Manchester, CT", "h2_specialty": "Piano & Specialty Movers in Manchester", "h2_packing": "Packing Services in Manchester, CT", "h2_commercial": "Commercial Moving in Manchester", "h2_why": "Why Manchester Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Manchester Today!" },
  { "town": "Newington", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "22-25 min", "slug": "movers-newington-ct", "title": "Best Movers in Newington, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Newington, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Newington, Connecticut", "h2_local": "Local Moving Services in Newington", "h2_ld": "Long Distance Moving from Newington, CT", "h2_specialty": "Piano & Specialty Movers in Newington", "h2_packing": "Packing Services in Newington, CT", "h2_commercial": "Commercial Moving in Newington", "h2_why": "Why Newington Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Newington Today!" },
  { "town": "Rocky Hill", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "25 min", "slug": "movers-rocky-hill-ct", "title": "Best Movers in Rocky Hill, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Rocky Hill, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Rocky Hill, Connecticut", "h2_local": "Local Moving Services in Rocky Hill", "h2_ld": "Long Distance Moving from Rocky Hill, CT", "h2_specialty": "Piano & Specialty Movers in Rocky Hill", "h2_packing": "Packing Services in Rocky Hill, CT", "h2_commercial": "Commercial Moving in Rocky Hill", "h2_why": "Why Rocky Hill Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Rocky Hill Today!" },
  { "town": "Stafford", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "28-32 min", "slug": "movers-stafford-ct", "title": "Best Movers in Stafford, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Stafford, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Stafford, Connecticut", "h2_local": "Local Moving Services in Stafford", "h2_ld": "Long Distance Moving from Stafford, CT", "h2_specialty": "Piano & Specialty Movers in Stafford", "h2_packing": "Packing Services in Stafford, CT", "h2_commercial": "Commercial Moving in Stafford", "h2_why": "Why Stafford Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Stafford Today!" },
  { "town": "Tolland", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "22-25 min", "slug": "movers-tolland-ct", "title": "Best Movers in Tolland, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Tolland, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Tolland, Connecticut", "h2_local": "Local Moving Services in Tolland", "h2_ld": "Long Distance Moving from Tolland, CT", "h2_specialty": "Piano & Specialty Movers in Tolland", "h2_packing": "Packing Services in Tolland, CT", "h2_commercial": "Commercial Moving in Tolland", "h2_why": "Why Tolland Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Tolland Today!" },
  { "town": "Vernon", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "20-25 min", "slug": "movers-vernon-ct", "title": "Best Movers in Vernon, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Vernon, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Vernon, Connecticut", "h2_local": "Local Moving Services in Vernon", "h2_ld": "Long Distance Moving from Vernon, CT", "h2_specialty": "Piano & Specialty Movers in Vernon", "h2_packing": "Packing Services in Vernon, CT", "h2_commercial": "Commercial Moving in Vernon", "h2_why": "Why Vernon Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Vernon Today!" },
  { "town": "West Hartford", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "20-23 min", "slug": "movers-west-hartford-ct", "title": "Best Movers in West Hartford, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in West Hartford, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in West Hartford, Connecticut", "h2_local": "Local Moving Services in West Hartford", "h2_ld": "Long Distance Moving from West Hartford, CT", "h2_specialty": "Piano & Specialty Movers in West Hartford", "h2_packing": "Packing Services in West Hartford, CT", "h2_commercial": "Commercial Moving in West Hartford", "h2_why": "Why West Hartford Residents Choose Castle Express", "cta": "Get a Free Moving Quote in West Hartford Today!" },
  { "town": "Wethersfield", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 2 - Core", "drive": "23-25 min", "slug": "movers-wethersfield-ct", "title": "Best Movers in Wethersfield, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Wethersfield, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Wethersfield, Connecticut", "h2_local": "Local Moving Services in Wethersfield", "h2_ld": "Long Distance Moving from Wethersfield, CT", "h2_specialty": "Piano & Specialty Movers in Wethersfield", "h2_packing": "Packing Services in Wethersfield, CT", "h2_commercial": "Commercial Moving in Wethersfield", "h2_why": "Why Wethersfield Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Wethersfield Today!" },
  { "town": "Belchertown", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "40-50 min", "slug": "movers-belchertown-ma", "title": "Best Movers in Belchertown, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Belchertown, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Belchertown, Massachusetts", "h2_local": "Local Moving Services in Belchertown", "h2_ld": "Long Distance Moving from Belchertown, MA", "h2_specialty": "Piano & Specialty Movers in Belchertown", "h2_packing": "Packing Services in Belchertown, MA", "h2_commercial": "Commercial Moving in Belchertown", "h2_why": "Why Belchertown Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Belchertown Today!" },
  { "town": "Brimfield", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "35-40 min", "slug": "movers-brimfield-ma", "title": "Best Movers in Brimfield, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Brimfield, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Brimfield, Massachusetts", "h2_local": "Local Moving Services in Brimfield", "h2_ld": "Long Distance Moving from Brimfield, MA", "h2_specialty": "Piano & Specialty Movers in Brimfield", "h2_packing": "Packing Services in Brimfield, MA", "h2_commercial": "Commercial Moving in Brimfield", "h2_why": "Why Brimfield Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Brimfield Today!" },
  { "town": "Easthampton", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "35-40 min", "slug": "movers-easthampton-ma", "title": "Best Movers in Easthampton, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Easthampton, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Easthampton, Massachusetts", "h2_local": "Local Moving Services in Easthampton", "h2_ld": "Long Distance Moving from Easthampton, MA", "h2_specialty": "Piano & Specialty Movers in Easthampton", "h2_packing": "Packing Services in Easthampton, MA", "h2_commercial": "Commercial Moving in Easthampton", "h2_why": "Why Easthampton Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Easthampton Today!" },
  { "town": "Granby", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "40-45 min", "slug": "movers-granby-ma", "title": "Best Movers in Granby, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Granby, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Granby, Massachusetts", "h2_local": "Local Moving Services in Granby", "h2_ld": "Long Distance Moving from Granby, MA", "h2_specialty": "Piano & Specialty Movers in Granby", "h2_packing": "Packing Services in Granby, MA", "h2_commercial": "Commercial Moving in Granby", "h2_why": "Why Granby Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Granby Today!" },
  { "town": "Granville", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "40-45 min", "slug": "movers-granville-ma", "title": "Best Movers in Granville, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Granville, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Granville, Massachusetts", "h2_local": "Local Moving Services in Granville", "h2_ld": "Long Distance Moving from Granville, MA", "h2_specialty": "Piano & Specialty Movers in Granville", "h2_packing": "Packing Services in Granville, MA", "h2_commercial": "Commercial Moving in Granville", "h2_why": "Why Granville Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Granville Today!" },
  { "town": "Hadley", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "35-40 min", "slug": "movers-hadley-ma", "title": "Best Movers in Hadley, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Hadley, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Hadley, Massachusetts", "h2_local": "Local Moving Services in Hadley", "h2_ld": "Long Distance Moving from Hadley, MA", "h2_specialty": "Piano & Specialty Movers in Hadley", "h2_packing": "Packing Services in Hadley, MA", "h2_commercial": "Commercial Moving in Hadley", "h2_why": "Why Hadley Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Hadley Today!" },
  { "town": "Hatfield", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "40-45 min", "slug": "movers-hatfield-ma", "title": "Best Movers in Hatfield, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Hatfield, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Hatfield, Massachusetts", "h2_local": "Local Moving Services in Hatfield", "h2_ld": "Long Distance Moving from Hatfield, MA", "h2_specialty": "Piano & Specialty Movers in Hatfield", "h2_packing": "Packing Services in Hatfield, MA", "h2_commercial": "Commercial Moving in Hatfield", "h2_why": "Why Hatfield Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Hatfield Today!" },
  { "town": "Holland", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "30-35 min", "slug": "movers-holland-ma", "title": "Best Movers in Holland, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Holland, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Holland, Massachusetts", "h2_local": "Local Moving Services in Holland", "h2_ld": "Long Distance Moving from Holland, MA", "h2_specialty": "Piano & Specialty Movers in Holland", "h2_packing": "Packing Services in Holland, MA", "h2_commercial": "Commercial Moving in Holland", "h2_why": "Why Holland Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Holland Today!" },
  { "town": "Monson", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "30-35 min", "slug": "movers-monson-ma", "title": "Best Movers in Monson, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Monson, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Monson, Massachusetts", "h2_local": "Local Moving Services in Monson", "h2_ld": "Long Distance Moving from Monson, MA", "h2_specialty": "Piano & Specialty Movers in Monson", "h2_packing": "Packing Services in Monson, MA", "h2_commercial": "Commercial Moving in Monson", "h2_why": "Why Monson Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Monson Today!" },
  { "town": "Northampton", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "37-45 min", "slug": "movers-northampton-ma", "title": "Best Movers in Northampton, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Northampton, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Northampton, Massachusetts", "h2_local": "Local Moving Services in Northampton", "h2_ld": "Long Distance Moving from Northampton, MA", "h2_specialty": "Piano & Specialty Movers in Northampton", "h2_packing": "Packing Services in Northampton, MA", "h2_commercial": "Commercial Moving in Northampton", "h2_why": "Why Northampton Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Northampton Today!" },
  { "town": "Palmer", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "35-40 min", "slug": "movers-palmer-ma", "title": "Best Movers in Palmer, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Palmer, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Palmer, Massachusetts", "h2_local": "Local Moving Services in Palmer", "h2_ld": "Long Distance Moving from Palmer, MA", "h2_specialty": "Piano & Specialty Movers in Palmer", "h2_packing": "Packing Services in Palmer, MA", "h2_commercial": "Commercial Moving in Palmer", "h2_why": "Why Palmer Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Palmer Today!" },
  { "town": "Russell", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "40-45 min", "slug": "movers-russell-ma", "title": "Best Movers in Russell, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Russell, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Russell, Massachusetts", "h2_local": "Local Moving Services in Russell", "h2_ld": "Long Distance Moving from Russell, MA", "h2_specialty": "Piano & Specialty Movers in Russell", "h2_packing": "Packing Services in Russell, MA", "h2_commercial": "Commercial Moving in Russell", "h2_why": "Why Russell Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Russell Today!" },
  { "town": "South Hadley", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "30-35 min", "slug": "movers-south-hadley-ma", "title": "Best Movers in South Hadley, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in South Hadley, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in South Hadley, Massachusetts", "h2_local": "Local Moving Services in South Hadley", "h2_ld": "Long Distance Moving from South Hadley, MA", "h2_specialty": "Piano & Specialty Movers in South Hadley", "h2_packing": "Packing Services in South Hadley, MA", "h2_commercial": "Commercial Moving in South Hadley", "h2_why": "Why South Hadley Residents Choose Castle Express", "cta": "Get a Free Moving Quote in South Hadley Today!" },
  { "town": "Tolland", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "40-45 min", "slug": "movers-tolland-ma", "title": "Best Movers in Tolland, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Tolland, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Tolland, Massachusetts", "h2_local": "Local Moving Services in Tolland", "h2_ld": "Long Distance Moving from Tolland, MA", "h2_specialty": "Piano & Specialty Movers in Tolland", "h2_packing": "Packing Services in Tolland, MA", "h2_commercial": "Commercial Moving in Tolland", "h2_why": "Why Tolland Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Tolland Today!" },
  { "town": "Wales", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 2 - Core", "drive": "35-40 min", "slug": "movers-wales-ma", "title": "Best Movers in Wales, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Wales, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Wales, Massachusetts", "h2_local": "Local Moving Services in Wales", "h2_ld": "Long Distance Moving from Wales, MA", "h2_specialty": "Piano & Specialty Movers in Wales", "h2_packing": "Packing Services in Wales, MA", "h2_commercial": "Commercial Moving in Wales", "h2_why": "Why Wales Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Wales Today!" },
  { "town": "Andover", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "25-28 min", "slug": "movers-andover-ct", "title": "Best Movers in Andover, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Andover, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Andover, Connecticut", "h2_local": "Local Moving Services in Andover", "h2_ld": "Long Distance Moving from Andover, CT", "h2_specialty": "Piano & Specialty Movers in Andover", "h2_packing": "Packing Services in Andover, CT", "h2_commercial": "Commercial Moving in Andover", "h2_why": "Why Andover Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Andover Today!" },
  { "town": "Avon", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "35-38 min", "slug": "movers-avon-ct", "title": "Best Movers in Avon, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Avon, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Avon, Connecticut", "h2_local": "Local Moving Services in Avon", "h2_ld": "Long Distance Moving from Avon, CT", "h2_specialty": "Piano & Specialty Movers in Avon", "h2_packing": "Packing Services in Avon, CT", "h2_commercial": "Commercial Moving in Avon", "h2_why": "Why Avon Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Avon Today!" },
  { "town": "Berlin", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "38-42 min", "slug": "movers-berlin-ct", "title": "Best Movers in Berlin, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Berlin, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Berlin, Connecticut", "h2_local": "Local Moving Services in Berlin", "h2_ld": "Long Distance Moving from Berlin, CT", "h2_specialty": "Piano & Specialty Movers in Berlin", "h2_packing": "Packing Services in Berlin, CT", "h2_commercial": "Commercial Moving in Berlin", "h2_why": "Why Berlin Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Berlin Today!" },
  { "town": "Bolton", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "25-28 min", "slug": "movers-bolton-ct", "title": "Best Movers in Bolton, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Bolton, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Bolton, Connecticut", "h2_local": "Local Moving Services in Bolton", "h2_ld": "Long Distance Moving from Bolton, CT", "h2_specialty": "Piano & Specialty Movers in Bolton", "h2_packing": "Packing Services in Bolton, CT", "h2_commercial": "Commercial Moving in Bolton", "h2_why": "Why Bolton Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Bolton Today!" },
  { "town": "Canton", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "40-42 min", "slug": "movers-canton-ct", "title": "Best Movers in Canton, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Canton, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Canton, Connecticut", "h2_local": "Local Moving Services in Canton", "h2_ld": "Long Distance Moving from Canton, CT", "h2_specialty": "Piano & Specialty Movers in Canton", "h2_packing": "Packing Services in Canton, CT", "h2_commercial": "Commercial Moving in Canton", "h2_why": "Why Canton Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Canton Today!" },
  { "town": "Columbia", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "28-32 min", "slug": "movers-columbia-ct", "title": "Best Movers in Columbia, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Columbia, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Columbia, Connecticut", "h2_local": "Local Moving Services in Columbia", "h2_ld": "Long Distance Moving from Columbia, CT", "h2_specialty": "Piano & Specialty Movers in Columbia", "h2_packing": "Packing Services in Columbia, CT", "h2_commercial": "Commercial Moving in Columbia", "h2_why": "Why Columbia Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Columbia Today!" },
  { "town": "Coventry", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "28-32 min", "slug": "movers-coventry-ct", "title": "Best Movers in Coventry, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Coventry, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Coventry, Connecticut", "h2_local": "Local Moving Services in Coventry", "h2_ld": "Long Distance Moving from Coventry, CT", "h2_specialty": "Piano & Specialty Movers in Coventry", "h2_packing": "Packing Services in Coventry, CT", "h2_commercial": "Commercial Moving in Coventry", "h2_why": "Why Coventry Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Coventry Today!" },
  { "town": "Durham", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "42-48 min", "slug": "movers-durham-ct", "title": "Best Movers in Durham, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Durham, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Durham, Connecticut", "h2_local": "Local Moving Services in Durham", "h2_ld": "Long Distance Moving from Durham, CT", "h2_specialty": "Piano & Specialty Movers in Durham", "h2_packing": "Packing Services in Durham, CT", "h2_commercial": "Commercial Moving in Durham", "h2_why": "Why Durham Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Durham Today!" },
  { "town": "Farmington", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "31 min", "slug": "movers-farmington-ct", "title": "Best Movers in Farmington, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Farmington, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Farmington, Connecticut", "h2_local": "Local Moving Services in Farmington", "h2_ld": "Long Distance Moving from Farmington, CT", "h2_specialty": "Piano & Specialty Movers in Farmington", "h2_packing": "Packing Services in Farmington, CT", "h2_commercial": "Commercial Moving in Farmington", "h2_why": "Why Farmington Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Farmington Today!" },
  { "town": "Hebron", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "28-32 min", "slug": "movers-hebron-ct", "title": "Best Movers in Hebron, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Hebron, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Hebron, Connecticut", "h2_local": "Local Moving Services in Hebron", "h2_ld": "Long Distance Moving from Hebron, CT", "h2_specialty": "Piano & Specialty Movers in Hebron", "h2_packing": "Packing Services in Hebron, CT", "h2_commercial": "Commercial Moving in Hebron", "h2_why": "Why Hebron Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Hebron Today!" },
  { "town": "Mansfield", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "30-35 min", "slug": "movers-mansfield-ct", "title": "Best Movers in Mansfield, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Mansfield, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Mansfield, Connecticut", "h2_local": "Local Moving Services in Mansfield", "h2_ld": "Long Distance Moving from Mansfield, CT", "h2_specialty": "Piano & Specialty Movers in Mansfield", "h2_packing": "Packing Services in Mansfield, CT", "h2_commercial": "Commercial Moving in Mansfield", "h2_why": "Why Mansfield Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Mansfield Today!" },
  { "town": "Marlborough", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "42-45 min", "slug": "movers-marlborough-ct", "title": "Best Movers in Marlborough, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Marlborough, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Marlborough, Connecticut", "h2_local": "Local Moving Services in Marlborough", "h2_ld": "Long Distance Moving from Marlborough, CT", "h2_specialty": "Piano & Specialty Movers in Marlborough", "h2_packing": "Packing Services in Marlborough, CT", "h2_commercial": "Commercial Moving in Marlborough", "h2_why": "Why Marlborough Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Marlborough Today!" },
  { "town": "Middletown", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "40 min", "slug": "movers-middletown-ct", "title": "Best Movers in Middletown, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Middletown, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Middletown, Connecticut", "h2_local": "Local Moving Services in Middletown", "h2_ld": "Long Distance Moving from Middletown, CT", "h2_specialty": "Piano & Specialty Movers in Middletown", "h2_packing": "Packing Services in Middletown, CT", "h2_commercial": "Commercial Moving in Middletown", "h2_why": "Why Middletown Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Middletown Today!" },
  { "town": "Plainville", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "38-42 min", "slug": "movers-plainville-ct", "title": "Best Movers in Plainville, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Plainville, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Plainville, Connecticut", "h2_local": "Local Moving Services in Plainville", "h2_ld": "Long Distance Moving from Plainville, CT", "h2_specialty": "Piano & Specialty Movers in Plainville", "h2_packing": "Packing Services in Plainville, CT", "h2_commercial": "Commercial Moving in Plainville", "h2_why": "Why Plainville Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Plainville Today!" },
  { "town": "Simsbury", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "30-35 min", "slug": "movers-simsbury-ct", "title": "Best Movers in Simsbury, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Simsbury, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Simsbury, Connecticut", "h2_local": "Local Moving Services in Simsbury", "h2_ld": "Long Distance Moving from Simsbury, CT", "h2_specialty": "Piano & Specialty Movers in Simsbury", "h2_packing": "Packing Services in Simsbury, CT", "h2_commercial": "Commercial Moving in Simsbury", "h2_why": "Why Simsbury Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Simsbury Today!" },
  { "town": "Southington", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "40-45 min", "slug": "movers-southington-ct", "title": "Best Movers in Southington, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Southington, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Southington, Connecticut", "h2_local": "Local Moving Services in Southington", "h2_ld": "Long Distance Moving from Southington, CT", "h2_specialty": "Piano & Specialty Movers in Southington", "h2_packing": "Packing Services in Southington, CT", "h2_commercial": "Commercial Moving in Southington", "h2_why": "Why Southington Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Southington Today!" },
  { "town": "Willington", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 3 - Extended", "drive": "28-30 min", "slug": "movers-willington-ct", "title": "Best Movers in Willington, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Willington, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Willington, Connecticut", "h2_local": "Local Moving Services in Willington", "h2_ld": "Long Distance Moving from Willington, CT", "h2_specialty": "Piano & Specialty Movers in Willington", "h2_packing": "Packing Services in Willington, CT", "h2_commercial": "Commercial Moving in Willington", "h2_why": "Why Willington Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Willington Today!" },
  { "town": "Amherst", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 3 - Extended", "drive": "40-50 min", "slug": "movers-amherst-ma", "title": "Best Movers in Amherst, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Amherst, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Amherst, Massachusetts", "h2_local": "Local Moving Services in Amherst", "h2_ld": "Long Distance Moving from Amherst, MA", "h2_specialty": "Piano & Specialty Movers in Amherst", "h2_packing": "Packing Services in Amherst, MA", "h2_commercial": "Commercial Moving in Amherst", "h2_why": "Why Amherst Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Amherst Today!" },
  { "town": "Charlton", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 3 - Extended", "drive": "50-55 min", "slug": "movers-charlton-ma", "title": "Best Movers in Charlton, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Charlton, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Charlton, Massachusetts", "h2_local": "Local Moving Services in Charlton", "h2_ld": "Long Distance Moving from Charlton, MA", "h2_specialty": "Piano & Specialty Movers in Charlton", "h2_packing": "Packing Services in Charlton, MA", "h2_commercial": "Commercial Moving in Charlton", "h2_why": "Why Charlton Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Charlton Today!" },
  { "town": "Deerfield", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 3 - Extended", "drive": "50-55 min", "slug": "movers-deerfield-ma", "title": "Best Movers in Deerfield, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Deerfield, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Deerfield, Massachusetts", "h2_local": "Local Moving Services in Deerfield", "h2_ld": "Long Distance Moving from Deerfield, MA", "h2_specialty": "Piano & Specialty Movers in Deerfield", "h2_packing": "Packing Services in Deerfield, MA", "h2_commercial": "Commercial Moving in Deerfield", "h2_why": "Why Deerfield Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Deerfield Today!" },
  { "town": "Oxford", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 3 - Extended", "drive": "55-60 min", "slug": "movers-oxford-ma", "title": "Best Movers in Oxford, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Oxford, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Oxford, Massachusetts", "h2_local": "Local Moving Services in Oxford", "h2_ld": "Long Distance Moving from Oxford, MA", "h2_specialty": "Piano & Specialty Movers in Oxford", "h2_packing": "Packing Services in Oxford, MA", "h2_commercial": "Commercial Moving in Oxford", "h2_why": "Why Oxford Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Oxford Today!" },
  { "town": "Southbridge", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 3 - Extended", "drive": "50-55 min", "slug": "movers-southbridge-ma", "title": "Best Movers in Southbridge, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Southbridge, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Southbridge, Massachusetts", "h2_local": "Local Moving Services in Southbridge", "h2_ld": "Long Distance Moving from Southbridge, MA", "h2_specialty": "Piano & Specialty Movers in Southbridge", "h2_packing": "Packing Services in Southbridge, MA", "h2_commercial": "Commercial Moving in Southbridge", "h2_why": "Why Southbridge Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Southbridge Today!" },
  { "town": "Sturbridge", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 3 - Extended", "drive": "45-50 min", "slug": "movers-sturbridge-ma", "title": "Best Movers in Sturbridge, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Sturbridge, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Sturbridge, Massachusetts", "h2_local": "Local Moving Services in Sturbridge", "h2_ld": "Long Distance Moving from Sturbridge, MA", "h2_specialty": "Piano & Specialty Movers in Sturbridge", "h2_packing": "Packing Services in Sturbridge, MA", "h2_commercial": "Commercial Moving in Sturbridge", "h2_why": "Why Sturbridge Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Sturbridge Today!" },
  { "town": "Ware", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 3 - Extended", "drive": "45-50 min", "slug": "movers-ware-ma", "title": "Best Movers in Ware, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Ware, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Ware, Massachusetts", "h2_local": "Local Moving Services in Ware", "h2_ld": "Long Distance Moving from Ware, MA", "h2_specialty": "Piano & Specialty Movers in Ware", "h2_packing": "Packing Services in Ware, MA", "h2_commercial": "Commercial Moving in Ware", "h2_why": "Why Ware Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Ware Today!" },
  { "town": "Webster", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 3 - Extended", "drive": "55-60 min", "slug": "movers-webster-ma", "title": "Best Movers in Webster, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Webster, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Webster, Massachusetts", "h2_local": "Local Moving Services in Webster", "h2_ld": "Long Distance Moving from Webster, MA", "h2_specialty": "Piano & Specialty Movers in Webster", "h2_packing": "Packing Services in Webster, MA", "h2_commercial": "Commercial Moving in Webster", "h2_why": "Why Webster Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Webster Today!" },
  { "town": "Whately", "state": "MA", "stateFull": "Massachusetts", "tier": "Tier 3 - Extended", "drive": "50-55 min", "slug": "movers-whately-ma", "title": "Best Movers in Whately, MA | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Whately, Massachusetts? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Whately, Massachusetts", "h2_local": "Local Moving Services in Whately", "h2_ld": "Long Distance Moving from Whately, MA", "h2_specialty": "Piano & Specialty Movers in Whately", "h2_packing": "Packing Services in Whately, MA", "h2_commercial": "Commercial Moving in Whately", "h2_why": "Why Whately Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Whately Today!" },
  { "town": "Ashford", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 4 - Outer Reach", "drive": "47 min", "slug": "movers-ashford-ct", "title": "Best Movers in Ashford, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Ashford, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Ashford, Connecticut", "h2_local": "Local Moving Services in Ashford", "h2_ld": "Long Distance Moving from Ashford, CT", "h2_specialty": "Piano & Specialty Movers in Ashford", "h2_packing": "Packing Services in Ashford, CT", "h2_commercial": "Commercial Moving in Ashford", "h2_why": "Why Ashford Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Ashford Today!" },
  { "town": "Bristol", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 4 - Outer Reach", "drive": "46 min", "slug": "movers-bristol-ct", "title": "Best Movers in Bristol, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Bristol, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Bristol, Connecticut", "h2_local": "Local Moving Services in Bristol", "h2_ld": "Long Distance Moving from Bristol, CT", "h2_specialty": "Piano & Specialty Movers in Bristol", "h2_packing": "Packing Services in Bristol, CT", "h2_commercial": "Commercial Moving in Bristol", "h2_why": "Why Bristol Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Bristol Today!" },
  { "town": "Cheshire", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 4 - Outer Reach", "drive": "52 min", "slug": "movers-cheshire-ct", "title": "Best Movers in Cheshire, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Cheshire, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Cheshire, Connecticut", "h2_local": "Local Moving Services in Cheshire", "h2_ld": "Long Distance Moving from Cheshire, CT", "h2_specialty": "Piano & Specialty Movers in Cheshire", "h2_packing": "Packing Services in Cheshire, CT", "h2_commercial": "Commercial Moving in Cheshire", "h2_why": "Why Cheshire Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Cheshire Today!" },
  { "town": "Harwinton", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 4 - Outer Reach", "drive": "40-45 min", "slug": "movers-harwinton-ct", "title": "Best Movers in Harwinton, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Harwinton, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Harwinton, Connecticut", "h2_local": "Local Moving Services in Harwinton", "h2_ld": "Long Distance Moving from Harwinton, CT", "h2_specialty": "Piano & Specialty Movers in Harwinton", "h2_packing": "Packing Services in Harwinton, CT", "h2_commercial": "Commercial Moving in Harwinton", "h2_why": "Why Harwinton Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Harwinton Today!" },
  { "town": "New Hartford", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 4 - Outer Reach", "drive": "40-45 min", "slug": "movers-new-hartford-ct", "title": "Best Movers in New Hartford, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in New Hartford, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in New Hartford, Connecticut", "h2_local": "Local Moving Services in New Hartford", "h2_ld": "Long Distance Moving from New Hartford, CT", "h2_specialty": "Piano & Specialty Movers in New Hartford", "h2_packing": "Packing Services in New Hartford, CT", "h2_commercial": "Commercial Moving in New Hartford", "h2_why": "Why New Hartford Residents Choose Castle Express", "cta": "Get a Free Moving Quote in New Hartford Today!" },
  { "town": "Torrington", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 4 - Outer Reach", "drive": "52 min", "slug": "movers-torrington-ct", "title": "Best Movers in Torrington, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Torrington, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Torrington, Connecticut", "h2_local": "Local Moving Services in Torrington", "h2_ld": "Long Distance Moving from Torrington, CT", "h2_specialty": "Piano & Specialty Movers in Torrington", "h2_packing": "Packing Services in Torrington, CT", "h2_commercial": "Commercial Moving in Torrington", "h2_why": "Why Torrington Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Torrington Today!" },
  { "town": "Wallingford", "state": "CT", "stateFull": "Connecticut", "tier": "Tier 4 - Outer Reach", "drive": "52 min", "slug": "movers-wallingford-ct", "title": "Best Movers in Wallingford, CT | Castle Express Moving & Storage", "meta": "Looking for reliable movers in Wallingford, Connecticut? Castle Express Moving & Storage offers local, long distance, piano moving & packing services. Free quotes!", "h1": "Professional Movers in Wallingford, Connecticut", "h2_local": "Local Moving Services in Wallingford", "h2_ld": "Long Distance Moving from Wallingford, CT", "h2_specialty": "Piano & Specialty Movers in Wallingford", "h2_packing": "Packing Services in Wallingford, CT", "h2_commercial": "Commercial Moving in Wallingford", "h2_why": "Why Wallingford Residents Choose Castle Express", "cta": "Get a Free Moving Quote in Wallingford Today!" }
];

export function getCityBySlug(slug) {
  return CITY_DATA.find(c => c.slug === slug) || null;
}

export function getAllSlugs() {
  return CITY_DATA.map(c => c.slug);
}

export function getCitiesByTier(tier) {
  return CITY_DATA.filter(c => c.tier === tier);
}
